### ISSUE TITLE
Problème SQL

### ISSUE THREAD

**Issue by BDN-fr** [Kamionn/lawyer#1]
Il manque la table 'gestionplanning' dans le fichier SQL on est obligé de la rajouter par nous même

**Comment by ShinHedaDev** [comment]
ça m'étonnerait qu'il y ça dans cette ressources ^^, à mon avis soit tu tes trompé soit tu as une autres version modifier, sinon passe sur le discord et nous regarderons ça ensemble :)

**Comment by BDN-fr** [comment]
Effectivement j'ai une version modifiée autant pour moi
